// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: gen_vscode_proj

#ifndef _GEN_VSCODE_PROJ_UI_H
#define _GEN_VSCODE_PROJ_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "lv_i18n.h"
#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_TabView1;
extern lv_obj_t * ui_TabPage1;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_TabPage2;
extern lv_obj_t * ui_TabView2;
extern lv_obj_t * ui_TabPage4;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_TabPage5;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_TabPage6;
extern lv_obj_t * ui_TabPage3;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Slider1;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Label5;
void ui_event_Panel3(lv_event_t * e);
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Label6;
void ui_event_Button2(lv_event_t * e);
extern lv_obj_t * ui_Button2;
void ui_event_Button3(lv_event_t * e);
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_TabPage7;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_TabPage8;
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(
    ui_img_img_1936905_computer_device_mac_pc_work_icon_png);    // assets\img\1936905_computer_device_mac_pc_work_icon.png

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
