#include <stdio.h>
#include <stdlib.h>

#include "lvgl.h"
#include "ui.h"

#include "lv_proj_hal_init.h"
#include "lv_demosAndExamples.h"

/*
    编译 & 运行 方式：
        第一种：cmake 手动编译：见 根目录的 CMakeLists.txt 的注释
        第二种：VsCode 执行 task.json，即 "运行和调试窗口" 直接 点 "Run"，或者 按 F5
*/

/* 一些使用注意：
    修改 配置文件 lv_conf.h、lv_drv_conf.h 等，要用对比工具辅助着来
    lv_tick_inc() 执行优先级应该高于 lv_timer_handler()，lv_timer_handler() 且也不能被中断打断（执行时先关闭中断再打开）
    lvgl 的 api 是 线程不安全的，每次在 线程里面 调用 lvgl 的 api，需要用同一个互斥锁包起来

    一些控件如 tabView 没有动画过渡了，在 lv_tabView.c 里面，将 LV_ANIM_OFF 都替换成 LV_ANIM_ON 即可~~按需改吧
    USE_WIN32DRV 使用：refer to https://github.com/lvgl/lv_port_pc_visual_studio，但是很多东西编译不过，弃之
*/

/* 对源码修改之处：
    sdl.c: sdl_event_handler(), elimnate the "exit(0);"

    win_drv.c:
        windrv_inity() 里面：
            // lv_task_create(msg_handler, 0, LV_TASK_PRIO_HIGHEST, NULL); this is old api not supported
            lv_timer_create(msg_handler, 10, NULL);
        WndProc() 里面：
            去掉 SetTimer()、lv_tick_inc()，因为不起作用..
    
*/

int main(int argc, char **argv)
{
    (void)argc; /*Unused*/
    (void)argv; /*Unused*/

    uint8_t ret = -1;

    /*Initialize LVGL*/
    lv_init();
    if(!lv_is_initialized()) {
        LV_LOG_ERROR("lv_init() failure"); return -1;
    }

    /*Initialize the HAL (display, input devices, tick) for LVGL*/
    ret = lv_proj_hal_init();
    if(ret < 0) { 
        LV_LOG_ERROR("win_hal_init() failure: %d", ret); return -1;
    }

    LV_LOG_USER("start show ui~");

    // lvgl_demosAndExamples_show();   // run lvgl demo
    ui_init();                   // run the project generated by SquareLine of dir "squareLine_proj"

    for(;;)
    {
        // do not call lv_timer_handler_run_in_period() instead, it`s very consume cpu
        lv_timer_handler();
        usleep(5000);

        if(lvgl_exit_flag) break;
    }

    LV_LOG_USER("THE END~");

    #ifdef __linux__
        #if USE_DRM
            drm_exit();
        #endif
        #if USE_FBDEV
            fbdev_exit();
        #endif
    #endif

    #if LV_ENABLE_GC || !LV_MEM_CUSTOM
        lv_deinit();
    #endif

    return 0;
}


