// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: bbl_screen_v2_main

#include "../ui.h"


// COMPONENT Switchformated

lv_obj_t * ui_Switchformated_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_Switchformated;
    cui_Switchformated = lv_switch_create(comp_parent);
    lv_obj_set_width(cui_Switchformated, 150);
    lv_obj_set_height(cui_Switchformated, 80);
    lv_obj_set_x(cui_Switchformated, -14);
    lv_obj_set_y(cui_Switchformated, 0);
    lv_obj_set_align(cui_Switchformated, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(cui_Switchformated, lv_color_hex(0x5E5E5E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_Switchformated, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(cui_Switchformated, lv_color_hex(0x009F5B), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(cui_Switchformated, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_SWITCHFORMATED_NUM);
    children[UI_COMP_SWITCHFORMATED_SWITCHFORMATED] = cui_Switchformated;
    lv_obj_add_event_cb(cui_Switchformated, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_Switchformated, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_Switchformated_create_hook(cui_Switchformated);
    return cui_Switchformated;
}

