// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: bbl_screen_v2_main

#ifndef _UI_COMP_SWITCHFORMATED_H
#define _UI_COMP_SWITCHFORMATED_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT Switchformated
#define UI_COMP_SWITCHFORMATED_SWITCHFORMATED 0
#define _UI_COMP_SWITCHFORMATED_NUM 1
lv_obj_t * ui_Switchformated_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
