// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: bbl_screen_v2_main

#include "../ui.h"

void ui_comp_Switchformated_create_hook(lv_obj_t * comp)
{
}
