// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: bbl_screen_v2_main

#ifndef _BBL_SCREEN_V2_MAIN_UI_H
#define _BBL_SCREEN_V2_MAIN_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

// #include "lv_i18n.h"
#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_TabViewMain;
extern lv_obj_t * ui_TabPageHome;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_TabViewPrinter;
extern lv_obj_t * ui_Axis;
extern lv_obj_t * ui_Panel3;
void ui_event_nozzleTempBtn(lv_event_t * e);
extern lv_obj_t * ui_nozzleTempBtn;
extern lv_obj_t * ui_Label1;
void ui_event_bedTempBtn(lv_event_t * e);
extern lv_obj_t * ui_bedTempBtn;
extern lv_obj_t * ui_Label2;
void ui_event_Button3(lv_event_t * e);
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Button4;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Button5;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Panel6;
extern lv_obj_t * ui_Panel7;
extern lv_obj_t * ui_Button7;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Button9;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Button10;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Button11;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_Button6;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Button8;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Panel8;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_Panel9;
extern lv_obj_t * ui_Filament;
extern lv_obj_t * ui_Panel12;
void ui_event_Switchformated_Switchformated(lv_event_t * e);
extern lv_obj_t * ui_Switchformated;
extern lv_obj_t * ui_Dropdown1;
void ui_event_TextArea1(lv_event_t * e);
extern lv_obj_t * ui_TextArea1;
extern lv_obj_t * ui_Keyboard1;
void ui_event_Checkbox1(lv_event_t * e);
extern lv_obj_t * ui_Checkbox1;
extern lv_obj_t * ui_Util;
extern lv_obj_t * ui_Slider1;
extern lv_obj_t * ui_Options;
extern lv_obj_t * ui_TabPagePrinter;
extern lv_obj_t * ui_TabPageModel;
extern lv_obj_t * ui_TabPageSettings;
extern lv_obj_t * ui_TabPageAssistant;
extern lv_obj_t * ui____initial_actions0;




void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
