// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: bbl_screen_v2_main

#include "ui.h"

void nozzleTempBtnClickedEventFun(lv_event_t * e)
{
	lv_event_code_t code = lv_event_get_code(e);
	lv_obj_t * obj = lv_event_get_target(e);
	void * user_data = lv_event_get_user_data(e);
	(void)obj;
	(void)user_data;
	if(code == LV_EVENT_CLICKED) {
		LV_LOG_USER("nozzleTempBtnClickedEventFun() LV_EVENT_CLICKED");
	}
}

void bedTempBtnClickedEventFun(lv_event_t * e)
{
	lv_event_code_t code = lv_event_get_code(e);
	lv_obj_t * obj = lv_event_get_target(e);
	void * user_data = lv_event_get_user_data(e);
	(void)obj;
	(void)user_data;
	if(code == LV_EVENT_CLICKED) {
		LV_LOG_USER("bedTempBtnClickedEventFun() LV_EVENT_CLICKED");
	}
}

void aaaaaaaa(lv_event_t * e)
{
	lv_event_code_t code = lv_event_get_code(e);
	lv_obj_t * obj = lv_event_get_target(e);
	void * user_data = lv_event_get_user_data(e);
	(void)obj;
	(void)user_data;
	if(code == LV_EVENT_CLICKED) {
		LV_LOG_USER("aaaaaaaa() LV_EVENT_CLICKED");
	}
}

void onfilamentSwitchChanged(lv_event_t * e)
{
	lv_event_code_t code = lv_event_get_code(e);
	lv_obj_t * obj = lv_event_get_target(e);
	void * user_data = lv_event_get_user_data(e);
	(void)user_data;
	if(code == LV_EVENT_VALUE_CHANGED) {
		char* str = lv_obj_has_state(obj, LV_STATE_CHECKED) ? "On" : "Off";
		LV_LOG_USER("onfilamentSwitchChanged() LV_EVENT_VALUE_CHANGED %s", str);
	}
}

void checkBoxCallBack(lv_event_t * e)
{
	lv_event_code_t code = lv_event_get_code(e);
	lv_obj_t * obj = lv_event_get_target(e);
	void * user_data = lv_event_get_user_data(e);
	(void)user_data;
	if(code == LV_EVENT_VALUE_CHANGED) {
		char* str = lv_obj_has_state(obj, LV_STATE_CHECKED) ? "On" : "Off";
		LV_LOG_USER("onfilamentSwitchChanged() LV_EVENT_VALUE_CHANGED %s", str);
	}
}
