// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: bbl_screen_v2_main

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void nozzleTempBtnClickedEventFun(lv_event_t * e);
void bedTempBtnClickedEventFun(lv_event_t * e);
void aaaaaaaa(lv_event_t * e);
void onfilamentSwitchChanged(lv_event_t * e);
void checkBoxCallBack(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
