// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: bbl_screen_v2_main

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t * ui_Screen1;
lv_obj_t * ui_TabViewMain;
lv_obj_t * ui_TabPageHome;
lv_obj_t * ui_Panel2;
lv_obj_t * ui_TabViewPrinter;
lv_obj_t * ui_Axis;
lv_obj_t * ui_Panel3;
void ui_event_nozzleTempBtn(lv_event_t * e);
lv_obj_t * ui_nozzleTempBtn;
lv_obj_t * ui_Label1;
void ui_event_bedTempBtn(lv_event_t * e);
lv_obj_t * ui_bedTempBtn;
lv_obj_t * ui_Label2;
void ui_event_Button3(lv_event_t * e);
lv_obj_t * ui_Button3;
lv_obj_t * ui_Label3;
lv_obj_t * ui_Button4;
lv_obj_t * ui_Label4;
lv_obj_t * ui_Button5;
lv_obj_t * ui_Label5;
lv_obj_t * ui_Panel6;
lv_obj_t * ui_Panel7;
lv_obj_t * ui_Button7;
lv_obj_t * ui_Label7;
lv_obj_t * ui_Button9;
lv_obj_t * ui_Label9;
lv_obj_t * ui_Button10;
lv_obj_t * ui_Label10;
lv_obj_t * ui_Button11;
lv_obj_t * ui_Label11;
lv_obj_t * ui_Button6;
lv_obj_t * ui_Label6;
lv_obj_t * ui_Button8;
lv_obj_t * ui_Label8;
lv_obj_t * ui_Panel8;
lv_obj_t * ui_Label12;
lv_obj_t * ui_Label13;
lv_obj_t * ui_Panel9;
lv_obj_t * ui_Filament;
lv_obj_t * ui_Panel12;
void ui_event_Switchformated_Switchformated(lv_event_t * e);
lv_obj_t * ui_Switchformated;
lv_obj_t * ui_Dropdown1;
void ui_event_TextArea1(lv_event_t * e);
lv_obj_t * ui_TextArea1;
lv_obj_t * ui_Keyboard1;
void ui_event_Checkbox1(lv_event_t * e);
lv_obj_t * ui_Checkbox1;
lv_obj_t * ui_Util;
lv_obj_t * ui_Slider1;
lv_obj_t * ui_Options;
lv_obj_t * ui_TabPagePrinter;
lv_obj_t * ui_TabPageModel;
lv_obj_t * ui_TabPageSettings;
lv_obj_t * ui_TabPageAssistant;
lv_obj_t * ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 32
    #error "LV_COLOR_DEPTH should be 32bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_nozzleTempBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        nozzleTempBtnClickedEventFun(e);
    }
}
void ui_event_bedTempBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        bedTempBtnClickedEventFun(e);
    }
}
void ui_event_Button3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        aaaaaaaa(e);
    }
}
void ui_event_Switchformated_Switchformated(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        onfilamentSwitchChanged(e);
    }
}
void ui_event_TextArea1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_FOCUSED) {
        _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_keyboard_set_target(ui_Keyboard1,  ui_TextArea1);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}
void ui_event_Checkbox1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        checkBoxCallBack(e);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    LV_EVENT_GET_COMP_CHILD = lv_event_register_id();

    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen1_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen1);
}
